#!/usr/bin/env php
<?php
$ske = require_once __DIR__ . DIRECTORY_SEPARATOR . 'ske.php';
$module = $ske->getModule('pkg/ske/ske');
$contents = $module->getContents();
$contents = preg_replace('{^#!/.+\r?\n<\?(php)?}', '', $contents, 1, $replaced);
if ($replaced) {
	$contents = strtr($contents, array(
		'__FILE__' => var_export($module->getRealPath(), true),
		'__DIR__' => var_export($module->getPackage()->getRealPath(), true),
	));
	eval($contents);
	exit(0);
}
$module->import();
